[package]
name = "backend_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.13"
ic-cdk = "0.17.1"
ic-cdk-timers = "0.11.0"
serde = { version = "1.0", features = ["derive"] }